dataset:
  train_images:       data/processed/train/images
  train_annotations:  data/processed/annotations/train.json
  val_images:         data/processed/val/images
  val_annotations:    data/processed/annotations/val.json

model:
  num_classes: 9
  batch_size: 8          # Tăng gấp đôi (mỗi GPU 4 ảnh) -> tận dụng 2 GPU
  epochs: 50
  learning_rate: 0.005   # Giữ nguyên, có thể tăng nhẹ nếu batch tăng gấp đôi
  num_workers: 4         # Tăng lên 4-8 để tải dữ liệu nhanh hơn
  val_every: 5

  
save_dir: models/faster_rcnn